language: java
jdk: oraclejdk8
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-central-1"  
  app: "kreamont-chatbot"
  env: "kreamont-chatbot-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-539329046248"
  on:
branch: master
zip_file: kreamont-chatbot-web/target/kreamont-chatbot-1.0-fatjar.zip
skip_cleanup: true