branch-defaults:
  master:
    environment: kreamont-chatbot-dev
environment-defaults:
  kreamont-chatbot-dev:
    branch: null
    repository: null
global:
  application_name: kreamont-chatbot
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Java 8 running
    on 64bit Amazon Linux/2.6.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
